### ISSUE TITLE
ENH: Output Efficiency 

### ISSUE THREAD

**Issue by patelraj425** [victoriyaforsythe/PyIRI#31]
# Description
I am using the PyIRI library to pull F2 peak heights for multiple days at different latitudes and longitudes. Currently, if I input an array of hours, latitudes, and longitudes, I get a matrix for F2 peak height for each hour element with each latitude/longitude set. However, I am interested in the F2 peak heights for a set of equal hours and latitude/longitudes. Essentially, each hour in the array has a corresponding latitude/longitude, and I want the F2 peak for JUST that combination and not all hours with all latitude/longitudes. Think of a spacecraft orbiting the Earth, I want just the F2 peak height at the spot the spacecraft is at, not the F2 peak of all latitudes/longitudes at that epoch.

Although the current method of the matrix output does give me what I want, takes unnecessarily long calculating all the unneeded values. 

## Potential impact
This feature would drastically improve the speed of my sims

**Comment by victoriyaforsythe** [comment]
Hi patelraj425! 
First of all, thank you for using PyIRI! 
Sorry it took me a while to respond, because I was thinking about your question and tried to come up with the solution. 
And, honestly, I have failed. 
The problem is that PyIRI uses matrix multiplication to evaluate all of the parameters, and this is it's main advantage in comparison to a regular IRI. Unfortunately, for you it is not an advantage, because for the satellite "fly through" type of input you need the model to work in a regular classical IRI-like way, meaning point-by-point evaluation, because for each location your time changes as well. 
Here is a link for the PyIRI manuscript, where I describe the way things work in PyIRI: https://essopenarchive.org/users/669292/articles/669824-pyiri-whole-globe-approach-to-the-international-reference-ionosphere-modeling-implemented-in-python

Please take a look, and if you are able to come up with a mathematical solution of the alternative to Equation 5, I would be happy to implement it and to add to the code. 

Let me explain it in a little bit mode details here what I mean:
We start with a coefficient matrix U that has [13, 76] size. Those coefficients come from CCIR or URSI files. They correspond to 13 diurnal functions and 76 global (spherical harmonics). We further take a Lon and Lat arrays and evaluate all 76 global functions (F_G), then we take time array and evaluate all 13 diurnal functions (F_D). Further, a matrix multiplication (F_D U) F_G produces parameters for the entire grid and the entire time array.

I don't see the right way how I can separate time and space dimensions for this problem...

So far, you have 2 options:
1) you can evaluate PyIRI for 1x1 grid and 30-min resolution time array in one step. Then for each satellite location find nearest time and grid point, or use interpolation in time and space for better quality. 
2) you can run PyIRI for each satellite location in a loop. It still will be faster than IRI. You will need to pass locations and time as 1-D arrays (e.g. alon = np.array([lon_sat[it]], alat = np.array([lat_sat[it]]), ahr =  np.array([time_sat[it]]) )

**Comment by patelraj425** [comment]
Hi Victoria,

No worries, makes sense. I will look into it and see if I can find a
solution.

I have another question about PyIRI. Is there any way to suppress the
output? I am running PyIRI in a loop and having an output printed every
time step is quite inefficient.

Thanks,
Raj

**Comment by aburrell** [comment]
Currently those are print statements and can't be surpressed.  We could fix this by using `logging` and sending the output there instead.
